### PR TITLE
Handle `Projection`s in `from_trait_ref`

### LINKED ISSUE #128: compilation issues with `hyper` and `tonic` crates
Steps to reproduce:

1. `git clone git@github.com:hyperium/tonic.git`
2. `cd tonic && cargo build`
3. `cargo crux-test --lib`

Ends up with the following error:

```
thread 'rustc' panicked at src/analyz/to_json.rs:140:26:
unexpected predicate kind: Binder { value: ProjectionPredicate(AliasTerm { args: [Self/#0], def_id: DefId(2:43315 ~ core[4e22]::future::future::Future::Output), .. }, Term::Ty(())), bound_vars: [] }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `hyper` (lib)

Caused by:
  process didn't exit successfully: `/Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/bin/mir-json-rustc-wrapper rustc --crate-name hyper --edition=2021 /Users/mpodhradsky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hyper-1.6.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --warn=unexpected_cfgs --check-cfg 'cfg(hyper_unstable_tracing)' --check-cfg 'cfg(hyper_unstable_ffi)' --cfg 'feature="client"' --cfg 'feature="default"' --cfg 'feature="http1"' --cfg 'feature="http2"' --cfg 'feature="server"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("capi", "client", "default", "ffi", "full", "http1", "http2", "nightly", "server", "tracing"))' -C metadata=011db9f2d3ff1887 -C extra-filename=-ba14d4c929bd4b9b --out-dir /private/tmp/tonic/target/aarch64-apple-darwin/debug/deps --target aarch64-apple-darwin -L dependency=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps -L dependency=/private/tmp/tonic/target/debug/deps --extern bytes=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libbytes-5026540b347d6b41.rmeta --extern futures_channel=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libfutures_channel-d93c1bbed572d53b.rmeta --extern futures_util=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libfutures_util-69235cfc66772ed2.rmeta --extern h2=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libh2-aa075fb0bfe626cc.rmeta --extern http=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libhttp-5b25adc06747c513.rmeta --extern http_body=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libhttp_body-671a7c0d0948f922.rmeta --extern httparse=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libhttparse-266fa0c91714a534.rmeta --extern httpdate=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libhttpdate-f1c917d027a3de36.rmeta --extern itoa=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libitoa-666df0c28451a465.rmeta --extern pin_project_lite=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libpin_project_lite-0050b6633782434b.rmeta --extern smallvec=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libsmallvec-8f822223c44fff95.rmeta --extern tokio=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libtokio-5b44ae937e0538de.rmeta --extern want=/private/tmp/tonic/target/aarch64-apple-darwin/debug/deps/libwant-eab08d62362ea2e2.rmeta --cap-lints allow` (exit status: 101)

```

Interestingly, running `crux-test` on `hyper` directly works:

1. `git clone git@github.com:hyperium/hyper.git`
2. `cd hyper`
3. `cargo crux-test --lib`

And the result is:
```
   Compiling hyper v1.6.0 (/private/tmp/hyper)
test build - extract output path - ["rustc", "--crate-name", "hyper", "--edition=2021", "src/lib.rs", "--error-format=json", "--json=diagnostic-rendered-ansi,artifacts,future-incompat", "--emit=dep-info,link", "-C", "embed-bitcode=no", "-C", "debuginfo=2", "-C", "split-debuginfo=unpacked", "--warn=unexpected_cfgs", "--check-cfg", "cfg(hyper_unstable_tracing)", "--check-cfg", "cfg(hyper_unstable_ffi)", "--test", "--cfg", "feature=\"default\"", "--check-cfg", "cfg(docsrs,test)", "--check-cfg", "cfg(feature, values(\"capi\", \"client\", \"default\", \"ffi\", \"full\", \"futures-util\", \"http1\", \"http2\", \"nightly\", \"server\", \"tracing\"))", "-C", "metadata=adb5d092a9b4a2ce", "-C", "extra-filename=-ed7ef5f05c68744d", "--out-dir", "/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps", "--target", "aarch64-apple-darwin", "-C", "incremental=/private/tmp/hyper/target/aarch64-apple-darwin/debug/incremental", "-L", "dependency=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps", "-L", "dependency=/private/tmp/hyper/target/debug/deps", "--extern", "bytes=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libbytes-5026540b347d6b41.rlib", "--extern", "form_urlencoded=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libform_urlencoded-051dabd7855d0055.rlib", "--extern", "futures_channel=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libfutures_channel-aea098b14e79c8fb.rlib", "--extern", "futures_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libfutures_util-b6f762886dbddb4f.rlib", "--extern", "http=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp-5b25adc06747c513.rlib", "--extern", "http_body=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp_body-671a7c0d0948f922.rlib", "--extern", "http_body_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp_body_util-833edee49c3f2499.rlib", "--extern", "pin_project_lite=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libpin_project_lite-0050b6633782434b.rlib", "--extern", "pretty_env_logger=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libpretty_env_logger-fbd2a848a7153a6b.rlib", "--extern", "serde=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libserde-5fc452ce2616e5ae.rlib", "--extern", "serde_json=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libserde_json-c0e95634946f2680.rlib", "--extern", "spmc=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libspmc-dee91ae5281f909a.rlib", "--extern", "tokio=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio-d59a7933f83f03e5.rlib", "--extern", "tokio_test=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio_test-e2adc64d52275086.rlib", "--extern", "tokio_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio_util-c621d4fe9da515f5.rlib", "--cfg", "crux", "-Z", "ub-checks=false", "-L", "/Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs", "--sysroot", "/Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs"]
test build - ["rustc", "--crate-name", "hyper", "--edition=2021", "src/lib.rs", "--error-format=json", "--json=diagnostic-rendered-ansi,artifacts,future-incompat", "--emit=dep-info,link", "-C", "embed-bitcode=no", "-C", "debuginfo=2", "-C", "split-debuginfo=unpacked", "--warn=unexpected_cfgs", "--check-cfg", "cfg(hyper_unstable_tracing)", "--check-cfg", "cfg(hyper_unstable_ffi)", "--cfg", "feature=\"default\"", "--check-cfg", "cfg(docsrs,test)", "--check-cfg", "cfg(feature, values(\"capi\", \"client\", \"default\", \"ffi\", \"full\", \"futures-util\", \"http1\", \"http2\", \"nightly\", \"server\", \"tracing\"))", "-C", "metadata=adb5d092a9b4a2ce", "-C", "extra-filename=-ed7ef5f05c68744d", "--out-dir", "/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps", "--target", "aarch64-apple-darwin", "-C", "incremental=/private/tmp/hyper/target/aarch64-apple-darwin/debug/incremental", "-L", "dependency=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps", "-L", "dependency=/private/tmp/hyper/target/debug/deps", "--extern", "bytes=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libbytes-5026540b347d6b41.rlib", "--extern", "form_urlencoded=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libform_urlencoded-051dabd7855d0055.rlib", "--extern", "futures_channel=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libfutures_channel-aea098b14e79c8fb.rlib", "--extern", "futures_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libfutures_util-b6f762886dbddb4f.rlib", "--extern", "http=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp-5b25adc06747c513.rlib", "--extern", "http_body=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp_body-671a7c0d0948f922.rlib", "--extern", "http_body_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp_body_util-833edee49c3f2499.rlib", "--extern", "pin_project_lite=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libpin_project_lite-0050b6633782434b.rlib", "--extern", "pretty_env_logger=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libpretty_env_logger-fbd2a848a7153a6b.rlib", "--extern", "serde=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libserde-5fc452ce2616e5ae.rlib", "--extern", "serde_json=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libserde_json-c0e95634946f2680.rlib", "--extern", "spmc=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libspmc-dee91ae5281f909a.rlib", "--extern", "tokio=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio-d59a7933f83f03e5.rlib", "--extern", "tokio_test=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio_test-e2adc64d52275086.rlib", "--extern", "tokio_util=/private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio_util-c621d4fe9da515f5.rlib", "--cfg", "crux", "-Z", "ub-checks=false", "-L", "/Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs", "--sysroot", "/Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs", "--cfg", "crux_top_level", "--crate-type", "rlib"]
linking 30 mir files into /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/hyper-ed7ef5f05c68744d.linked-mir.json
  inputs: /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhyper-ed7ef5f05c68744d.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libstd.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libcore.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libcompiler_builtins.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/librustc_std_workspace_core.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/liballoc.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libcrucible.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/liblibc.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libunwind.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libcfg_if.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libminiz_oxide.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libadler2.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libhashbrown.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/librustc_std_workspace_alloc.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libstd_detect.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/librustc_demangle.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libaddr2line.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libgimli.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libobject.mir /Users/mpodhradsky/Applications/mir-json-macos-14-ARM64/rlibs/libmemchr.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp-5b25adc06747c513.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libfnv-0cfbf1a72f5c7255.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libbytes-5026540b347d6b41.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libitoa-666df0c28451a465.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libhttp_body-671a7c0d0948f922.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libtokio-d59a7933f83f03e5.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libpin_project_lite-0050b6633782434b.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libmio-3a062ff887ea7d54.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/liblibc-f9167017af0d4db3.mir /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/libsocket2-c52099898c5d95d0.mir
generated test script /private/tmp/hyper/target/aarch64-apple-darwin/debug/deps/hyper-ed7ef5f05c68744d
    Finished `test` profile [unoptimized + debuginfo] target(s) in 13.60s
     Running unittests src/lib.rs (target/aarch64-apple-darwin/debug/deps/hyper-ed7ef5f05c68744d)

[Crux-MIR] ---- FINAL RESULTS ----
[Crux] All goals discharged through internal simplification.
[Crux] Overall status: Valid.
```

If you have recommendations what else to do to narrow down the issue please let me know.

### PR DESCRIPTION
**Pull request by RyanGlScott**
This patch equips `from_trait_ref` to handle clauses of the form `where Foo: Bar<Item = Type>`.

Fixes #128.

### CODE REVIEW

File: src/analyz/to_json.rs [hunk 1]
```diff
@@ -134,14 +134,22 @@ impl<'tcx> TraitInst<'tcx> {
...
-                    ty::ClauseKind::Trait(x) => x,
+                let pred_def_id = match tcx.instantiate_bound_regions_with_erased(pred.kind()) {
+                    // Corresponds to `where Foo: Bar`. Get the DefId for `Bar`.
+                    ty::ClauseKind::Trait(tpred) => {
+                        assert_eq!(tpred.polarity, ty::PredicatePolarity::Positive);
+                        tpred.trait_ref.def_id
+                    },
+                    // Corresponds to `where Foo: Bar<Item = Type>`. Get the
+                    // DefId for `Bar` by looking up `Item`'s parent.
+                    ty::ClauseKind::Projection(ppred) => tcx.parent(ppred.projection_term.def_id),
```
Comment (spernsteiner) [inline src/analyz/to_json.rs:145]: I think it may be safe to ignore `ClauseKind::Projection`, actually.  It should only appear in conjunction with a `ClauseKind::Trait` for the same trait.  As documented [here](https://doc.rust-lang.org/stable/nightly-rustc/rustc_type_ir/predicate/struct.ProjectionPredicate.html), the syntax `Foo: Bar<Assoc = T>` produces a `ClauseKind::Trait` representing `Foo: Bar` and a `ClauseKind::Projection` representing `<Foo as Bar>::Assoc == T`.  But mentioning `<Foo as Bar>` is nonsensical unless `Foo: Bar` is also known somehow.  I think the only way you can have the `ClauseKind::Projection` without the corresponding `ClauseKind::Trait` is if `Foo` is a concrete type like `<&'static u8 as Deref>::Target == u8` instead of a generic parameter, but in this case `Foo` is always the parameter `Self`.

Note it's also harmless to leave this as-is, since we already have logic to deduplicate the supertraits we discover.
